server:
  port: 8090
  error:
    include:
      message: true

spring:
  application:
    name: rococo-api

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

niffler-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc'
---