create table if not exists country
(
    id                     binary(16)    unique not null default (UUID_TO_BIN(UUID(), true)),
    name                   varchar(50)   unique not null,
    primary key (id)
);

insert into country(name) values ('Фиджи');
insert into country(name) values ('Танзания');
insert into country(name) values ('Западная Сахара');
insert into country(name) values ('Канада');
insert into country(name) values ('Соединенные Штаты');
insert into country(name) values ('Казахстан');
insert into country(name) values ('Узбекистан');
insert into country(name) values ('Папуа - Новая Гвинея');
insert into country(name) values ('Индонезия');
insert into country(name) values ('Аргентина');
insert into country(name) values ('Чили');
insert into country(name) values ('Демократическая Республика Конго');
insert into country(name) values ('Сомали');
insert into country(name) values ('Кения');
insert into country(name) values ('Судан');
insert into country(name) values ('Чад');
insert into country(name) values ('Гаити');
insert into country(name) values ('Доминиканская Республика');
insert into country(name) values ('Россия');
insert into country(name) values ('Багамские острова');
insert into country(name) values ('Фолклендские острова');
insert into country(name) values ('Норвегия');
insert into country(name) values ('Гренландия');
insert into country(name) values ('Восточный Тимор');
insert into country(name) values ('Южно-Африканская Республика');
insert into country(name) values ('Лесото');
insert into country(name) values ('Мексика');
insert into country(name) values ('Уругвай');
insert into country(name) values ('Бразилия');
insert into country(name) values ('Боливия');
insert into country(name) values ('Перу');
insert into country(name) values ('Колумбия');
insert into country(name) values ('Панама');
insert into country(name) values ('Коста-Рика');
insert into country(name) values ('Никарагуа');
insert into country(name) values ('Гондурас');
insert into country(name) values ('Сальвадор');
insert into country(name) values ('Гватемала');
insert into country(name) values ('Белиз');
insert into country(name) values ('Венесуэла');
insert into country(name) values ('Гайана');
insert into country(name) values ('Суринам');
insert into country(name) values ('Франция');
insert into country(name) values ('Эквадор');
insert into country(name) values ('Пуэрто-Рико');
insert into country(name) values ('Ямайка');
insert into country(name) values ('Куба');
insert into country(name) values ('Зимбабве');
insert into country(name) values ('Ботсвана');
insert into country(name) values ('Намибия');
insert into country(name) values ('Сенегал');
insert into country(name) values ('Мали');
insert into country(name) values ('Мавритания');
insert into country(name) values ('Бенин');
insert into country(name) values ('Нигер');
insert into country(name) values ('Нигерия');
insert into country(name) values ('Камерун');
insert into country(name) values ('Того');
insert into country(name) values ('Гана');
insert into country(name) values ('Кот-д\'Ивуар');
insert into country(name) values ('Гвинея');
insert into country(name) values ('Гвинея-Бисау');
insert into country(name) values ('Либерия');
insert into country(name) values ('Сьерра-Леоне');
insert into country(name) values ('Буркина-Фасо');
insert into country(name) values ('Центральноафриканская Республика');
insert into country(name) values ('Республика Конго');
insert into country(name) values ('Габон');
insert into country(name) values ('Экваториальная Гвинея');
insert into country(name) values ('Замбия');
insert into country(name) values ('Малави');
insert into country(name) values ('Мозамбик');
insert into country(name) values ('Эсватини');
insert into country(name) values ('Ангола');
insert into country(name) values ('Бурунди');
insert into country(name) values ('Израиль');
insert into country(name) values ('Ливан');
insert into country(name) values ('Мадагаскар');
insert into country(name) values ('Палестина');
insert into country(name) values ('Гамбия');
insert into country(name) values ('Тунис');
insert into country(name) values ('Алжир');
insert into country(name) values ('Иордания');
insert into country(name) values ('Объединенные Арабские Эмираты');
insert into country(name) values ('Катар');
insert into country(name) values ('Кувейт');
insert into country(name) values ('Ирак');
insert into country(name) values ('Оман');
insert into country(name) values ('Вануату');
insert into country(name) values ('Камбоджа');
insert into country(name) values ('Таиланд');
insert into country(name) values ('Лаос');
insert into country(name) values ('Мьянма');
insert into country(name) values ('Вьетнам');
insert into country(name) values ('Корейская Народно-Демократическая Республика');
insert into country(name) values ('Республика Корея');
insert into country(name) values ('Монголия');
insert into country(name) values ('Индия');
insert into country(name) values ('Бангладеш');
insert into country(name) values ('Бутан');
insert into country(name) values ('Непал');
insert into country(name) values ('Пакистан');
insert into country(name) values ('Афганистан');
insert into country(name) values ('Таджикистан');
insert into country(name) values ('Киргизия');
insert into country(name) values ('Туркменистан');
insert into country(name) values ('Иран');
insert into country(name) values ('Сирия');
insert into country(name) values ('Армения');
insert into country(name) values ('Швеция');
insert into country(name) values ('Беларусь');
insert into country(name) values ('Украина');
insert into country(name) values ('Польша');
insert into country(name) values ('Австрия');
insert into country(name) values ('Венгрия');
insert into country(name) values ('Молдова');
insert into country(name) values ('Румыния');
insert into country(name) values ('Литва');
insert into country(name) values ('Латвия');
insert into country(name) values ('Эстония');
insert into country(name) values ('Германия');
insert into country(name) values ('Болгария');
insert into country(name) values ('Греция');
insert into country(name) values ('Турция');
insert into country(name) values ('Албания');
insert into country(name) values ('Хорватия');
insert into country(name) values ('Швейцария');
insert into country(name) values ('Люксембург');
insert into country(name) values ('Бельгия');
insert into country(name) values ('Нидерланды');
insert into country(name) values ('Португалия');
insert into country(name) values ('Испания');
insert into country(name) values ('Ирландия');
insert into country(name) values ('Новая Каледония');
insert into country(name) values ('Соломоновы острова');
insert into country(name) values ('Новая Зеландия');
insert into country(name) values ('Австралия');
insert into country(name) values ('Шри-Ланка');
insert into country(name) values ('Китай');
insert into country(name) values ('Тайвань');
insert into country(name) values ('Италия');
insert into country(name) values ('Дания');
insert into country(name) values ('Соединенное Королевство');
insert into country(name) values ('Исландия');
insert into country(name) values ('Азербайджан');
insert into country(name) values ('Грузия');
insert into country(name) values ('Филиппины');
insert into country(name) values ('Малайзия');
insert into country(name) values ('Бруней');
insert into country(name) values ('Словения');
insert into country(name) values ('Финляндия');
insert into country(name) values ('Словакия');
insert into country(name) values ('Чешская Республика');
insert into country(name) values ('Эритрея');
insert into country(name) values ('Япония');
insert into country(name) values ('Парагвай');
insert into country(name) values ('Йемен');
insert into country(name) values ('Саудовская Аравия');
insert into country(name) values ('Северный Кипр');
insert into country(name) values ('Кипр');
insert into country(name) values ('Марокко');
insert into country(name) values ('Египет');
insert into country(name) values ('Ливия');
insert into country(name) values ('Эфиопия');
insert into country(name) values ('Джибути');
insert into country(name) values ('Сомалиленд');
insert into country(name) values ('Уганда');
insert into country(name) values ('Руанда');
insert into country(name) values ('Босния и Герцеговина');
insert into country(name) values ('Северная Македония');
insert into country(name) values ('Сербия');
insert into country(name) values ('Черногория');
insert into country(name) values ('Косово');
insert into country(name) values ('Тринидад и Тобаго');
insert into country(name) values ('Южный Судан');